# Generated by Django 3.1.1 on 2020-09-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=200, verbose_name='postTitle')),
                ('postAuthor', models.CharField(max_length=50, verbose_name='authorName')),
                ('postText', models.TextField(verbose_name='postText')),
                ('postDateCreate', models.DateTimeField(auto_now_add=True, verbose_name='dateOfCreate')),
                ('postDatePublication', models.DateTimeField(blank=True, null=True, verbose_name='dateOfPub')),
                ('postDateLastRefresh', models.DateTimeField(auto_now=True, verbose_name='dateOfRefresh')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.category')),
            ],
            options={
                'ordering': ['postDateCreate'],
            },
        ),
    ]
